/* Court Capital UI. Valuation results are fixed, assumption-based research. */
'use strict';
const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(x,n=2)=>Number.isFinite(+x)?(+x).toLocaleString('en-US',{minimumFractionDigits:n,maximumFractionDigits:n}):'—',money=(x,n=2)=>Number.isFinite(+x)?(x<0?'−$':'$')+num(Math.abs(x),n):'—',pct=x=>num(x*100,2)+'%', signed=x=>(x>0?'+':'')+money(x),cls=x=>x<0?'negative':x>0?'positive':'';
let model,sourceData,market,selected='RISE',lastSnapshot,pricePaths={},verification={};
const vols={RISE:.40,PRIME:.30,ANCHOR:.22,ROLE:.32,VET:.26,REBOUND:.52}, borrows={RISE:.09,PRIME:.05,ANCHOR:.03,ROLE:.07,VET:.06,REBOUND:.16};
const table=(heads,rows)=>'<table><thead><tr>'+heads.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
const metric=(label,value,detail='')=>'<div class="metric"><span class="label">'+esc(label)+'</span><span class="value">'+value+'</span><span class="detail">'+esc(detail)+'</span></div>';
const empty=t=>'<div class="empty">'+esc(t)+'</div>';
function notify(msg,error=false){$('message').textContent=msg;$('message').classList.toggle('error',error);}
function action(fn){try{const r=fn();notify(r?.message||'Paper account updated.',r?.ok===false);renderMarket();}catch(e){notify(e.message,true);}}
function exportFile(name,text,type='application/json'){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function lineChart(points,{width=760,height=210,color='#155a80'}={}){if(!points.length)return empty('No observations.');let ys=points.map(x=>x.y),min=Math.min(...ys),max=Math.max(...ys);let pad=Math.max((max-min)*.16,max*.025,.01);min=Math.max(0,min-pad);max+=pad;let dx=Math.max(1,points.at(-1).x-points[0].x),X=v=>62+(v-points[0].x)/dx*(width-88),Y=v=>height-32-(v-min)/(max-min)*(height-58);let path=points.map((p,i)=>(i?'L':'M')+X(p.x).toFixed(1)+','+Y(p.y).toFixed(1)).join(' ');return `<svg class="plot" viewBox="0 0 ${width} ${height}" role="img" aria-label="Simulated price path in dollars">${[0,.5,1].map(q=>{let v=min+(max-min)*q;return `<line x1="60" x2="${width-18}" y1="${Y(v)}" y2="${Y(v)}" stroke="#dce4e9"/><text x="50" y="${Y(v)+5}" text-anchor="end">${num(v)}</text>`}).join('')}<path d="${path}" fill="none" stroke="${color}" stroke-width="2.5"/><circle cx="${X(points.at(-1).x)}" cy="${Y(points.at(-1).y)}" r="3" fill="${color}"/><text x="62" y="${height-7}">Session ${points[0].x}</text><text x="${width-20}" y="${height-7}" text-anchor="end">${points.at(-1).x}</text></svg>`;}
function barChart(labels,values){let w=650,h=230,max=Math.max(...values)*1.15||1,bw=64;return `<svg class="plot" viewBox="0 0 ${w} ${h}" role="img" aria-label="Expected per-unit cash distributions by year">${[0,.5,1].map(q=>`<line x1="55" x2="630" y1="${190-q*170}" y2="${190-q*170}" stroke="#dce4e9"/><text x="46" y="${194-q*170}" text-anchor="end">${money(q*max)}</text>`).join('')}${values.map((v,i)=>`<rect x="${82+i*109}" y="${190-v/max*170}" width="${bw}" height="${v/max*170}" fill="#155a80"/><text x="${114+i*109}" y="${182-v/max*170}" text-anchor="middle">${money(v)}</text><text x="${114+i*109}" y="218" text-anchor="middle">${esc(labels[i])}</text>`).join('')}</svg>`;}
function getBook(t){return lastSnapshot?.orderBook?.[t]||{bid:market.prices[t]*.997,ask:market.prices[t]*1.003,bids:[],asks:[]};}
function renderMarket(){let s=market.snapshot();lastSnapshot=s;for(let a of market.assets){let p=pricePaths[a.ticker]??=[];let last=p.at(-1);if(!last||last.x!==market.day||last.y!==market.prices[a.ticker])p.push({x:market.day,y:market.prices[a.ticker]});if(p.length>500)p.shift();}
$('sessionDay').textContent=`Session ${market.day} / 1,260`;$('sessionRate').textContent=`Cash rate ${pct(market.rf)} · debit rate ${pct(market.marginRate)}`;
$('accountMetrics').innerHTML=metric('Account equity',money(s.equity),'Cash + equity + options + unsettled futures P/L')+metric('Cash balance',money(s.cash),'Includes realized variation margin')+metric('Net P/L',`<span class="${cls(s.pnl)}">${signed(s.pnl)}</span>`,'Against $100,000 opening equity')+metric('Initial requirement',money(s.initialRequired+s.pendingReserve),'Holdings, paid options and reserved orders')+metric('Margin headroom',money(s.equity-s.maintenanceRequired),'Equity less maintenance requirement');
$('quotes').innerHTML=market.assets.map(a=>{let t=a.ticker,b=getBook(t),change=market.prices[t]/market.initialPrices[t]-1;return `<tr class="selectable ${t===selected?'selected':''}" data-ticker="${t}" tabindex="0" role="button" aria-label="Select ${t}"><td><span class="ticker">${t}</span><small>${esc(a.name)}</small></td><td class="num">${money(market.prices[t])}</td><td class="num ${cls(change)}">${pct(change)}</td><td class="num">${money(b.bid)} / ${money(b.ask)}</td><td class="num">${pct(a.borrowRate)}</td></tr>`}).join('');
$('quotes').querySelectorAll('[data-ticker]').forEach(el=>{let f=()=>{selected=el.dataset.ticker;$('stockTicker').value=selected;$('valTicker').value=selected;$('stockLimit').value=market.prices[selected].toFixed(2);renderMarket();renderValuation();};el.onclick=f;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();f();}}});
$('priceTitle').textContent=selected+' · synthetic market path';$('priceChart').innerHTML=lineChart(pricePaths[selected]);let b=getBook(selected),depth=[];for(let i=0;i<Math.max(b.bids?.length||0,b.asks?.length||0);i++){let x=b.bids[i]||{},y=b.asks[i]||{};depth.push([num(x.qty??x.size,0),money(x.price),money(y.price),num(y.qty??y.size,0)]);}$('orderBook').innerHTML=depth.length?table(['Bid units','Bid price','Ask price','Ask units'],depth):empty('No executable quotes available.');
let a=market.assets.find(x=>x.ticker===selected),d=model.assets.find(x=>x.ticker===selected);$('selectedFacts').innerHTML=[['Opening modeled value',money(d.fair_value_per_unit/(a.floatShares/100000))],['Year-one distribution / unit',money(d.expected_annual_payout_per_unit[0]/(a.floatShares/100000))],[d.liquidation_pv_share!==undefined?'Terminal cash share of PV':'Protected share of model PV',pct(d.liquidation_pv_share??d.contracted_pv_share)],['Assumed annual volatility',pct(a.vol)],['Available locates',num(s.assets.find(x=>x.ticker===selected).borrowRemaining,0)+' units'],['Final income horizon','1,260 sessions']].map(([k,v])=>`<div><span>${k}</span><b>${v}</b></div>`).join('');
let pos=s.positions||[];if(!Array.isArray(pos))pos=Object.entries(pos).map(([ticker,qty])=>({ticker,qty}));$('positions').innerHTML=pos.length?table(['Equity','Units','Mid','Market value','Direction'],pos.map(p=>[esc(p.ticker),num(p.qty??p.quantity,0),money(market.prices[p.ticker]),money((p.qty??p.quantity)*market.prices[p.ticker]),(p.qty??p.quantity)<0?'Short; owes distributions':'Long'])):empty('No stock positions. Submit a paper order to begin.');
let orders=s.openOrders||[];$('orders').innerHTML=orders.length?table(['Order','Equity','Action','Remaining','Limit','Status',''],orders.map(o=>[esc(o.id),esc(o.ticker),esc(o.side),num(o.remaining??o.remainingQty??o.qty,0),money(o.limit),esc(o.status),`<button class="mini" data-cancel="${o.id}">Cancel</button>`])):empty('No resting orders. Market orders execute immediately or cancel unfilled quantity.');$('orders').querySelectorAll('[data-cancel]').forEach(el=>el.onclick=()=>action(()=>market.cancel(el.dataset.cancel)));
renderDerivatives(s);renderLedger(s);renderLiveRisk(s);renderTicket();}
function renderTicket(){let t=$('stockTicker').value,b=getBook(t),qty=+$('stockQty').value,side=$('stockSide').value,p=(side==='buy'||side==='cover')?b.ask:b.bid;$('stockLimit').disabled=$('stockType').value!=='limit';$('ticketEstimate').textContent=`Indicative first-level notional ${money(qty*p)}; execution can cross depth. Commission ${pct(market.feeRate)}. Shares: 50% initial / 30% maintenance simulator settings.`;}
function qDCF(cf,r){return cf.reduce((total,c,q)=>total+c/(1+r)**((q+1)/4),0);}
function renderValuation(){let a=model.assets.find(x=>x.ticker===$('valTicker').value),r=(+$('valRate').value + +$('valPremium').value)/100,units=+$('valPart').value;if(!Number.isFinite(r)||r<0||!Number.isFinite(units)||units<=0)return;
let cf=a.expected_annual_payout_per_unit,pv=qDCF(a.expected_quarterly_payout_per_unit,r),cashSum=cf.reduce((x,y)=>x+y,0);
$('valuationMetrics').innerHTML=metric('Modeled equity / unit',money(pv),'Discounted at '+pct(r))+metric('Selected position value',money(pv*units),num(units,0)+' units; hypothetical opening DCF')+metric('Liquidation share of PV',pct(a.liquidation_pv_share),'Baseline 12% discount rate')+metric('Year-one cash / value',pct(cf[0]/pv),'Cash yield; not an expected total return')+metric('Expected five-year cash',money(cashSum*units),'Includes final reserve; no guaranteed principal');
$('cashflowChart').innerHTML=barChart(['Year 1','Year 2','Year 3','Year 4','Year 5'],cf);
$('cashflowTable').innerHTML=table(['Year','Commercial revenue','Payout / unit','Of which liquidation'],cf.map((x,i)=>[i+1,money(a.expected_annual_commercial_revenue[i],0),money(x,3),money(i===4?a.liquidation_mean_per_unit:0,3)]));
let revenue=a.expected_annual_commercial_revenue[0];$('waterfall').innerHTML=table(['Expected first-year business','Amount'],[['Collected commercial sales',money(revenue,0)],['Player IP / service fee · 25%',money(revenue*.25,0)],['Conditional third-party rights · 5%',money(revenue*.05,0)],['Fulfillment / marketing · 30%',money(revenue*.30,0)],['Platform servicing · 2%',money(revenue*.02,0)],['Base fixed costs',money(a.fixed_expenses,0)],['Expected operating profit',money(a.expected_annual_operating_profit[0],0)],['Expected shareholder cash',money(cf[0]*100000,0)]]);
$('waterfall').innerHTML+='<p class="note">Shareholder cash reflects quarterly reserve interest, 21% positive-profit tax and 90% payout. Tax and insolvency are nonlinear; multiplying mean annual profit is not an exact reconciliation.</p>';
$('valuationTable').innerHTML=table(['Fictional venture','Sales budget','Equity / unit','Year-one cash','Liquidation PV share','PV P5–P95'],model.assets.map(x=>[esc(x.ticker)+'<small>'+esc(x.name)+'</small>',money(x.gross_revenue/1e6)+'m',money(x.fair_value_per_unit),money(x.expected_annual_payout_per_unit[0]),pct(x.liquidation_pv_share),money(x.pv_p05)+' – '+money(x.pv_p95)]));
$('rateSensitivity').innerHTML=table(['Risk-free rate','Required return','Per-unit value','Change vs 4% cash-rate case'],[.02,.04,.06].map(rf=>{let value=qDCF(a.expected_quarterly_payout_per_unit,rf+.08),base=qDCF(a.expected_quarterly_payout_per_unit,.12);return[pct(rf),pct(rf+.08),money(value),pct(value/base-1)]}));renderBusiness();}
function renderBusiness(){let a=model.assets.find(x=>x.ticker===$('valTicker').value),f=a.initial_funding,rev=a.expected_annual_commercial_revenue[0];
$('fundingTable').innerHTML=table(['Selected venture · '+a.ticker,'Initial amount'],[['Investor proceeds',money(f.gross_investor_equity_proceeds,0)],['Operating reserve',money(f.operating_cash_reserve,0)],['Issuance fee · 2%',money(f.issuance_fee,0)],['Residual upfront license consideration',money(f.upfront_ip_license_payment,0)],['Unfunded requirement',money(f.financing_gap,0)]]);
$('stakeholders').innerHTML=table(['Recipient','Expected first-year cash source','Amount'],[['Player brand owner','Ongoing IP / service fee',money(rev*.25,0)],['Authorized rights holders','Conditional team/league IP fee',money(rev*.05,0)],['Platform','Servicing actual sales',money(rev*.02,0)],['Shareholders','After-tax distributions',money(a.expected_annual_payout_per_unit[0]*100000,0)]]);
let n=+$('bizIssuers').value,t=+$('bizTurnover').value,factor=+$('bizRevenue').value/100,b=model.platform_business.assumptions;
if(!Number.isFinite(n)||n<1||!Number.isFinite(factor)||factor<0)return;
let servicing=n*b.average_annual_collected_servicing_per_issuer*factor,trading=n*b.average_issuer_dcf_equity*b.active_float_fraction*t*b.trading_fee_per_dollar,cost=b.fixed_operating_budget+n*b.annual_per_issuer_compliance_servicing_cost,contribution=b.average_annual_collected_servicing_per_issuer*factor-b.annual_per_issuer_compliance_servicing_cost,breakeven=contribution>0?Math.ceil(b.fixed_operating_budget/contribution):null,issue=n*b.average_issuer_dcf_equity*.02;
$('businessMetrics').innerHTML=metric('Annual servicing',money(servicing,0),'2% of assumed collected revenue')+metric('Conditional trading fees',money(trading,0),'Excluded when turnover is zero')+metric('Recurring operating result',money(servicing+trading-cost,0),'Before income tax; modeled annual scale')+metric('No-trading break-even',breakeven?num(breakeven,0)+' issuers':'Not attainable','At selected servicing revenue level')+metric('One-time issuance fees',money(issue,0),'Not included in recurring operating result');
$('businessTable').innerHTML=table(['Scale assumption','Value'],[['Annual fixed platform costs',money(b.fixed_operating_budget,0)],['Annual issuer-specific cost',money(n*b.annual_per_issuer_compliance_servicing_cost,0)],['Annual active-float trading notional',money(n*b.average_issuer_dcf_equity*b.active_float_fraction*t,0)],['Annual costs in total',money(cost,0)],['Operating result without trading',money(servicing-cost,0)]]);
$('rightsRegister').innerHTML=table(['Evidence required','Why it matters','Prototype status'],[['Player IP license','Scope, term, channels, conflicts, termination and economic rights','Fictional; not signed'],['Sponsor contracts','Separate binding minimums from sales targets; verify credit risk','40% budget floor assumed in years 1–2'],['Team / league / group rights','Permission for logos, uniforms, footage or group appearances','Not obtained; assumed fee is not approval'],['Independent related-party review','Prevent commercial contracts disguising playing compensation','Required; not performed'],['Revenue reconciliation','Trace sales receipts through expenses, taxes, reserves and dividends','Implemented for synthetic cash flows'],['Investor / venue permissions','Offering eligibility, transfer restrictions, custody and market access','Partner-dependent; no securities offered']]);}
function normalCDF(x){let t=1/(1+.2316419*Math.abs(x)),p=1-0.3989422804*Math.exp(-x*x/2)*t*(.319381530+t*(-.356563782+t*(1.781477937+t*(-1.821255978+t*1.330274429))));return x<0?1-p:p;}
function bs(S,K,T,r,q,v,type){if(T<=0)return Math.max(0,type==='call'?S-K:K-S);let d1=(Math.log(S/K)+(r-q+v*v/2)*T)/(v*Math.sqrt(T)),d2=d1-v*Math.sqrt(T);return type==='call'?S*Math.exp(-q*T)*normalCDF(d1)-K*Math.exp(-r*T)*normalCDF(d2):K*Math.exp(-r*T)*normalCDF(-d2)-S*Math.exp(-q*T)*normalCDF(-d1);}
function annualDividend(a){let year=Math.min(4,Math.floor(market.day/252));return a.distributions?.[year]??a.dividend;}
function renderDerivativeQuotes(){
if(!market)return;
let t=$('futureTicker').value,a=market.assets.find(x=>x.ticker===t),S=market.prices[t],days=+$('futureDays').value,qty=+$('futureQty').value,sign=$('futureSide').value==='long'?1:-1;
if(market.day+days>1260){$('futureEstimate').textContent='This maturity is beyond the five-year business-liquidation horizon and will be rejected.';}
else {let fair=market.forwardPrice(t,days),execution=fair*(1+sign*.0005*market.liquidityFactor);$('futureEstimate').innerHTML=`Carry mark <b>${money(fair,4)}</b> per unit · indicative entry <b>${money(execution,4)}</b>.<br>Initial margin <b>${money(S*qty*.10)}</b> and opening fee <b>${money(S*qty*market.feeRate)}</b>. One underlying unit per futures unit; scheduled terminal cash stays in its exact quarter.`;}
t=$('optionTicker').value;a=market.assets.find(x=>x.ticker===t);S=market.prices[t];
let K=+$('optionStrike').value,T=+$('optionDays').value/252,q=annualDividend(a)/Math.max(.01,S),type=$('optionType').value,contracts=+$('optionQty').value;
if(market.day+T*252>1260){$('optionEstimate').textContent='This maturity is beyond the five-year business-liquidation horizon and will be rejected.';return;}
if(!Number.isFinite(K)||K<=0||!Number.isFinite(contracts)||contracts<=0||S<=0){$('optionEstimate').textContent='Enter a positive strike and contract quantity for an unexpired equity.';return;}
try {let g=CourtEngine.optionGreeks(S,K,T,market.rf,a.vol,q,type),ask=g.value*(1+.025*market.liquidityFactor),premium=ask*100*contracts,fee=premium*market.feeRate;$('optionEstimate').innerHTML=`Model mark <b>${money(g.value*100)}</b> per 100-unit contract. Indicative total cash debit <b>${money(premium+fee)}</b>, including modeled ask spread and commission.<br>Delta ${num(g.delta,3)} per unit · Vega ${money(g.vega,4)} per unit / +1 vol point. European continuous-yield approximation; not a calibrated finite-business option price.`;}catch(e){$('optionEstimate').textContent=e.message;}}
function renderDerivatives(s){renderDerivativeQuotes();let fs=s.futures.filter(x=>x.status==='open'),os=s.options.filter(x=>x.status==='open');$('futuresTable').innerHTML=fs.length?table(['ID','Underlying','Side','Units','Expiry','Mark','Settled variation','Unsettled P/L',''],fs.map(x=>[esc(x.id),esc(x.ticker),esc(x.side),num(x.qty,0),esc(x.expiry),money(x.mark),money(x.variation),money(x.unrealized),`<button class="mini" data-fclose="${x.id}">Close</button>`])):empty('No open futures. Margin is collateral, not the purchase price.');$('optionsTable').innerHTML=os.length?table(['ID','Underlying','Payoff','Contracts × units','Strike','Expiry','Position value',''],os.map(x=>[esc(x.id),esc(x.ticker),esc(x.type),num(x.qty,0)+' × '+num(x.multiplier,0),money(x.strike),esc(x.expiry),money(x.value),`<button class="mini" data-oclose="${x.id}">Sell to close</button>`])):empty('No open options. Long holders can lose the full premium.');$('futuresTable').querySelectorAll('[data-fclose]').forEach(b=>b.onclick=()=>action(()=>market.closeFuture(b.dataset.fclose)));$('optionsTable').querySelectorAll('[data-oclose]').forEach(b=>b.onclick=()=>action(()=>market.closeOption(b.dataset.oclose)));}
function renderLedger(s){$('ledgerMetrics').innerHTML=metric('Stock market value',money(s.stockValue),'Signed positions; shorts are liabilities')+metric('Option market value',money(s.optionsValue),'Unrealized value of purchased options')+metric('Execution fees',money(s.fees),'Cumulative')+metric('Stock-loan expense',money(s.borrowCost),'Cumulative')+metric('Net distributions',money(s.dividends),'Long receipts less short obligations');let entries=[...(market.ledger||[])].reverse();$('ledgerTable').innerHTML=entries.length?table(['Session','Entry','Cash movement','Cash after','Detail'],entries.slice(0,200).map(e=>[esc(e.day),esc(e.type??e.event),money(e.amount??e.cashChange??e.delta),money(e.cashAfter??e.cash),esc(e.description??e.message??e.detail)])):empty('The ledger will record trades, funding, distributions, fees and settlement.');}
function renderLiveRisk(s){$('liveRisk').innerHTML=table(['Quantity','Value','Meaning'],[['Gross exposure',money(s.grossExposure),'Absolute equity value + futures spot notional + long option market value; not delta-equivalent risk'],['Initial holdings requirement',money(s.initialRequired),'50% stock gross + 10% futures notional + 100% long option value'],['Resting-order reservation',money(s.pendingReserve),'Additional margin budget committed to open orders'],['Maintenance requirement',money(s.maintenanceRequired),'30% stock gross + 7.5% futures notional + option value; not a guaranteed loss limit'],['Restricted collateral',money(s.collateralRequired),'150% short market value + futures initial collateral'],['Available buying power',money(s.availableBuyingPower),'Additional stock-notional budget at 50% margin after reservations'],['Unsettled futures P/L',money(s.futuresUnrealized),'Included in account equity; becomes cash at the next daily settlement'],['Accrued net interest',money(s.interest),'Short-sale collateral does not earn interest; cash borrowing pays the debit rate'],['Liquidation deficit',money(s.deficit),s.insolvent?'Account insolvent; reset required':'No negative-balance protection is assumed']]);}
function renderRisk(){let p=model.portfolio;$('riskMetrics').innerHTML=metric('Paired scenarios',num(model.draws,0),'Same economic drivers across claims')+metric('Portfolio loss VaR95',pct(p.funding_loss_var95),'Five-year discounted funding shortfall')+metric('Portfolio loss ES95',pct(p.funding_loss_es95),'Mean worst 5% funding shortfall')+metric('Shared-factor downside',pct(model.common_factor_stress.equal_dollar_pv_change),'Bottom-decile common-demand subset')+metric('Baseline required return','12.00%','Assumption; not a projected observed return');
$('portfolioRisk').innerHTML=table(['Allocation','Loss VaR95','Loss ES95','P(PV below cost)'],[...model.assets.map(a=>[a.ticker,pct(a.risk.funding_loss_var95),pct(a.risk.funding_loss_es95),pct(a.risk.pv_shortfall_probability)]),['Equal-dollar six-claim basket',pct(p.funding_loss_var95),pct(p.funding_loss_es95),pct(p.pv_shortfall_probability)]]);let max=Math.max(...model.assets.map(a=>a.pv_p95))*1.05,w=650,h=270,X=v=>100+v/max*510;$('riskChart').innerHTML=`<svg class="plot" viewBox="0 0 ${w} ${h}" role="img" aria-label="5th, 50th and 95th percentile of per-unit present value">${[0,.5,1].map(q=>`<line x1="${X(q*max)}" x2="${X(q*max)}" y1="10" y2="238" stroke="#dce4e9"/><text x="${X(q*max)}" y="259" text-anchor="middle">${money(q*max)}</text>`).join('')}${model.assets.map((a,i)=>`<text x="5" y="${29+i*39}">${a.ticker}</text><line x1="${X(a.pv_p05)}" x2="${X(a.pv_p95)}" y1="${25+i*39}" y2="${25+i*39}" stroke="#8da8ba" stroke-width="4"/><circle cx="${X(a.pv_p50)}" cy="${25+i*39}" r="5" fill="#155a80"/>`).join('')}</svg>`;
let names={commercial_sales_minus_25pct:'Sales budget −25%',injury_every_year:'Injury stress in every year',common_unsold_sales_shock_minus_30pct:'Unsold commercial demand −30%'};$('stressTable').innerHTML=table(['Scenario',...model.assets.map(a=>a.ticker),'Equal-dollar basket'],Object.entries(model.stress_tests).map(([k,v])=>[names[k]||esc(k),...model.assets.map(a=>pct(v.change_from_base_pct[a.ticker])),pct(v.equal_dollar_portfolio_pv_change)]));$('assumptions').innerHTML=table(['Assumption','Specification'],Object.entries(model.assumptions).filter(([k])=>!['source_ids','excluded','seasons','renewal_outcomes'].includes(k)).map(([k,v])=>[esc(k.replaceAll('_',' ')),esc(typeof v==='object'?JSON.stringify(v):v)]))+'<p class="note">The DCF model excludes '+model.assumptions.excluded.map(esc).join(', ')+'. The trading module separately demonstrates some of those market frictions. Its time-series prices are not the same stochastic process as the venture cash-flow model.</p>';}
const coverage=[['Cash-flow rights','Modeled','Five-year fictional commercial equity. Quarterly profit distributions; final remaining cash, not guaranteed principal.'],['Spot execution','Implemented','Market / limit orders, simulated three-level depth, bid–ask spreads, partial fills, execution fees, reservations and cancellation.'],['Short selling','Implemented','Locate limits, signed liabilities, borrow costs, dividend compensation, recall scenarios and adverse buy-in.'],['Financing and margin','Implemented','Cash interest, debit interest, initial and maintenance requirements, collateral limits and forced liquidation.'],['Futures','Implemented','Finite expiry, scheduled-distribution carry, long/short positions, daily cash variation and final cash settlement.'],['Options','Implemented with approximation','Fully paid long European calls/puts, 100-unit multiplier, continuous-yield Black–Scholes, mark-to-model liquidation and expiry.'],['Corporate actions','Simplified','Quarterly assumed distributions and wealth-neutral unit splits when supported. Contract-upside and injury repricing scenarios.'],['Volatility / liquidity events','Scenario engine','Seeded correlated price changes, finite depth, liquidity withdrawal, rate and market shocks. No historical calibration.'],['Portfolio analysis','Research model','20,000 paired business cash-flow scenarios, concentration, discounted funding-loss VaR/ES and conditional macro stress.'],['Settlement','Simplified','Immediate T+0 cash settlement. Real US equities generally use T+1; no settlement-failure model.'],['Market participants','Simplified','Synthetic external liquidity. No real matching counterparties, exchange connection, deposits or withdrawals.'],['Market integrity','Partial','Input validation, risk limits and 10% order-price protection. No surveillance, KYC/AML, licensed clearing or exchange-grade security.'],['Not implemented','Explicit exclusions','American exercise/assignment, option writing, multi-leg strategies, real securities lending, convertible shares, auctions calibrated to a venue, dividends with record-date/T+1 handling, tax lots, routing/NBBO, regulatory reporting, bankruptcy recovery and real clearing-member default waterfalls.']];
function renderResearch(){let src=sourceData.sources||sourceData;$('sources').innerHTML=src.map((x,i)=>`<div class="source"><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.id||('S'+(i+1)))} · ${esc(x.title||x.name)}</a><p>${esc(x.claim||x.supports||x.use||x.notes||x.description||'Primary reference.')} ${esc(x.date||'')}</p></div>`).join('');$('mechanicsTable').innerHTML=table(['Area','Coverage','Implementation / limitation'],coverage.map(r=>r.map(esc)));$('verification').innerHTML=verification.status?'<p>'+esc(verification.summary||verification.status)+'</p><p class="note">'+esc(verification.details||'')+'</p>':'<p>Reproducible model and accounting tests are supplied in the download. See the verification manifest for checks performed.</p>';}
function bind(){document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab));});$('stepDay').onclick=()=>action(()=>market.advance(1));$('stepMonth').onclick=()=>action(()=>market.advance(21));$('stepQuarter').onclick=()=>action(()=>market.advance(63));$('applyShock').onclick=()=>action(()=>market.shock($('shockKind').value,selected));$('split').onclick=()=>action(()=>{let r=market.split(selected,2);if(r.ok){pricePaths[selected]=(pricePaths[selected]||[]).map(p=>({...p,y:p.y/2}));$('stockLimit').value=market.prices[selected].toFixed(2);}return r;});$('stockForm').onsubmit=e=>{e.preventDefault();action(()=>market.order({ticker:$('stockTicker').value,side:$('stockSide').value,qty:+$('stockQty').value,type:$('stockType').value,limit:+$('stockLimit').value}));};$('stockTicker').onchange=()=>{selected=$('stockTicker').value;$('valTicker').value=selected;$('stockLimit').value=market.prices[selected].toFixed(2);renderMarket();renderValuation();};['stockQty','stockSide','stockType','stockLimit'].forEach(x=>$(x).oninput=renderTicket);['valTicker','valRate','valPremium','valPart'].forEach(x=>$(x).oninput=renderValuation);['bizIssuers','bizTurnover','bizRevenue'].forEach(x=>$(x).oninput=renderBusiness);['futureTicker','futureSide','futureQty','futureDays','optionTicker','optionType','optionQty','optionStrike','optionDays'].forEach(x=>$(x).oninput=renderDerivativeQuotes);$('optionTicker').addEventListener('change',()=>{$('optionStrike').value=market.prices[$('optionTicker').value].toFixed(2);renderDerivativeQuotes();});$('futureForm').onsubmit=e=>{e.preventDefault();action(()=>market.future({ticker:$('futureTicker').value,side:$('futureSide').value,qty:+$('futureQty').value,days:+$('futureDays').value}));};$('optionForm').onsubmit=e=>{e.preventDefault();action(()=>market.option({ticker:$('optionTicker').value,type:$('optionType').value,qty:+$('optionQty').value,strike:+$('optionStrike').value,days:+$('optionDays').value}));};$('reset').onclick=()=>$('resetDialog').showModal();$('cancelReset').onclick=()=>$('resetDialog').close();$('confirmReset').onclick=()=>{$('resetDialog').close();market.reset();pricePaths={};action(()=>({ok:true,message:'Account reset to $100,000 and the original seeded market.'}));};$('exportState').onclick=()=>exportFile('Court_Capital_Paper_Account.json',JSON.stringify(market.exportState(),null,2));$('exportLedger').onclick=()=>{let rows=market.ledger||[],keys=[...new Set(rows.flatMap(x=>Object.keys(x)))],q=x=>'"'+String(typeof x==='object'?JSON.stringify(x):x??'').replaceAll('"','""')+'"';exportFile('Court_Capital_Ledger.csv',[keys.map(q).join(','),...rows.map(x=>keys.map(k=>q(x[k])).join(','))].join('\n'),'text/csv');};}
async function init(){try{[model,sourceData]=await Promise.all([fetch('data/commercial_model.json').then(r=>{if(!r.ok)throw Error('Model results unavailable.');return r.json();}),fetch('data/sources.json').then(r=>r.json())]);try{verification=await fetch('data/verification.json').then(r=>r.json());}catch{}let overrides=model.assets.map(a=>({ticker:a.ticker,name:a.name,price:a.fair_value_per_unit,dividend:a.expected_annual_payout_per_unit[0],distributions:a.expected_annual_payout_per_unit,quarterlyDistributions:a.expected_quarterly_payout_per_unit,vol:vols[a.ticker],borrowRate:borrows[a.ticker],borrowAvailable:15000,floatShares:100000,guaranteedYears:a.guaranteed_years}));market=new CourtEngine.Market(20261007,overrides);let options=market.assets.map(a=>`<option value="${a.ticker}">${a.ticker} · ${esc(a.name)}</option>`).join('');['stockTicker','valTicker','futureTicker','optionTicker'].forEach(id=>$(id).innerHTML=options);$('stockLimit').value=market.prices[selected].toFixed(2);$('optionStrike').value=market.prices[selected].toFixed(2);bind();renderMarket();renderValuation();renderRisk();renderResearch();notify('Ready. $100,000 in paper cash. Select a venture, place an order, or explore business economics. Export the account before reloading; this session is not stored.');}catch(e){notify('The research application could not start: '+e.message+'. Serve this folder through a local web server or use the hosted version.',true);console.error(e);}}
init();
